package exceptionHandling;
import java.util.Scanner;
public class ExceptionHandle
{
    public static void main(String[] args)
    {
        try
        {
            Scanner input = new Scanner(System.in);
            int x, y;
            System.out.print("Input x & y: ");
            x = input.nextInt();
            y = input.nextInt();
            System.out.println("Result = "+(x/y));

            /* int[] a = new int[4];  // array declare
            a[4] = 4;
            System.out.println(a[4]); */     // array bound demo
        }
        /* catch(RuntimeException r)
        {
            System.out.println("Exception = "+r);
        } */
        catch(Exception e)
        {
            System.out.println("Exception = "+e);
        }

        /* catch(ArrayIndexOutOfBoundsException e) // error & not print the last line
        {
            System.out.println("Exception = "+e);
        } */

        finally // when we try to run the code in any way
        {
            System.out.println("Last line of the code.");
        }
    }
}
